Contract {
    interface: Interface {
      fragments: [
        [EventFragment],    [EventFragment],    [EventFragment],
        [EventFragment],    [EventFragment],    [EventFragment],
        [EventFragment],    [EventFragment],    [EventFragment],
        [EventFragment],    [EventFragment],    [EventFragment],
        [EventFragment],    [EventFragment],    [EventFragment],
        [EventFragment],    [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment],
        [FunctionFragment], [FunctionFragment], [FunctionFragment]
      ],
      _abiCoder: AbiCoder { coerceFunc: null },
      functions: {
        'ADDRESSES_PROVIDER()': [FunctionFragment],
        'BRIDGE_PROTOCOL_FEE()': [FunctionFragment],
        'FLASHLOAN_PREMIUM_TOTAL()': [FunctionFragment],
        'FLASHLOAN_PREMIUM_TO_PROTOCOL()': [FunctionFragment],
        'MAX_NUMBER_RESERVES()': [FunctionFragment],
        'MAX_STABLE_RATE_BORROW_SIZE_PERCENT()': [FunctionFragment],
        'backUnbacked(address,uint256,uint256)': [FunctionFragment],
        'borrow(address,uint256,uint256,uint16,address)': [FunctionFragment],
        'configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))': [FunctionFragment],
        'deposit(address,uint256,address,uint16)': [FunctionFragment],
        'dropReserve(address)': [FunctionFragment],
        'finalizeTransfer(address,address,address,uint256,uint256,uint256)': [FunctionFragment],
        'flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)': [FunctionFragment],
        'flashLoanSimple(address,address,uint256,bytes,uint16)': [FunctionFragment],
        'getConfiguration(address)': [FunctionFragment],
        'getEModeCategoryData(uint8)': [FunctionFragment],
        'getReserveAddressById(uint16)': [FunctionFragment],
        'getReserveData(address)': [FunctionFragment],
        'getReserveNormalizedIncome(address)': [FunctionFragment],
        'getReserveNormalizedVariableDebt(address)': [FunctionFragment],
        'getReservesList()': [FunctionFragment],
        'getUserAccountData(address)': [FunctionFragment],
        'getUserConfiguration(address)': [FunctionFragment],
        'getUserEMode(address)': [FunctionFragment],
        'initReserve(address,address,address,address,address)': [FunctionFragment],
        'liquidationCall(address,address,address,uint256,bool)': [FunctionFragment],
        'mintToTreasury(address[])': [FunctionFragment],
        'mintUnbacked(address,uint256,address,uint16)': [FunctionFragment],
        'rebalanceStableBorrowRate(address,address)': [FunctionFragment],
        'repay(address,uint256,uint256,address)': [FunctionFragment],
        'repayWithATokens(address,uint256,uint256)': [FunctionFragment],
        'repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)': [FunctionFragment],
        'rescueTokens(address,address,uint256)': [FunctionFragment],
        'resetIsolationModeTotalDebt(address)': [FunctionFragment],
        'setConfiguration(address,(uint256))': [FunctionFragment],
        'setReserveInterestRateStrategyAddress(address,address)': [FunctionFragment],
        'setUserEMode(uint8)': [FunctionFragment],
        'setUserUseReserveAsCollateral(address,bool)': [FunctionFragment],
        'supply(address,uint256,address,uint16)': [FunctionFragment],
        'supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)': [FunctionFragment],
        'swapBorrowRateMode(address,uint256)': [FunctionFragment],
        'updateBridgeProtocolFee(uint256)': [FunctionFragment],
        'updateFlashloanPremiums(uint128,uint128)': [FunctionFragment],
        'withdraw(address,uint256,address)': [FunctionFragment]
      },
      errors: {},
      events: {
        'BackUnbacked(address,address,uint256,uint256)': [EventFragment],
        'Borrow(address,address,address,uint256,uint8,uint256,uint16)': [EventFragment],
        'FlashLoan(address,address,address,uint256,uint8,uint256,uint16)': [EventFragment],
        'IsolationModeTotalDebtUpdated(address,uint256)': [EventFragment],
        'LiquidationCall(address,address,address,uint256,uint256,address,bool)': [EventFragment],
        'MintUnbacked(address,address,address,uint256,uint16)': [EventFragment],
        'MintedToTreasury(address,uint256)': [EventFragment],
        'RebalanceStableBorrowRate(address,address)': [EventFragment],
        'Repay(address,address,address,uint256,bool)': [EventFragment],
        'ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)': [EventFragment],
        'ReserveUsedAsCollateralDisabled(address,address)': [EventFragment],
        'ReserveUsedAsCollateralEnabled(address,address)': [EventFragment],
        'Supply(address,address,address,uint256,uint16)': [EventFragment],
        'SwapBorrowRateMode(address,address,uint8)': [EventFragment],
        'UserEModeSet(address,uint8)': [EventFragment],
        'Withdraw(address,address,address,uint256)': [EventFragment]
      },
      structs: {},
      deploy: ConstructorFragment {
        name: null,
        type: 'constructor',
        inputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        gas: null,
        _isFragment: true
      },
      _isInterface: true
    },
    provider: EthersProviderWrapper {
      _isProvider: true,
      _events: [],
      _emitted: { block: -2 },
      formatter: Formatter { formats: [Object] },
      anyNetwork: false,
      _networkPromise: Promise { [Object] },
      _maxInternalBlockNumber: -1024,
      _lastBlockNumber: -2,
      _pollingInterval: 4000,
      _fastQueryDate: 0,
      connection: { url: 'http://localhost:8545' },
      _nextId: 42,
      _hardhatProvider: BackwardsCompatibilityProviderAdapter {
        _wrapped: FixedGasProvider {
          _wrapped: AutomaticSenderProvider {
            _wrapped: [HardhatNetworkProvider],
            _wrappedProvider: [HardhatNetworkProvider]
          },
          _wrappedProvider: AutomaticSenderProvider {
            _wrapped: [HardhatNetworkProvider],
            _wrappedProvider: [HardhatNetworkProvider]
          },
          _gasLimit: 30000000
        },
        _provider: FixedGasProvider {
          _wrapped: AutomaticSenderProvider {
            _wrapped: [HardhatNetworkProvider],
            _wrappedProvider: [HardhatNetworkProvider]
          },
          _wrappedProvider: AutomaticSenderProvider {
            _wrapped: [HardhatNetworkProvider],
            _wrappedProvider: [HardhatNetworkProvider]
          },
          _gasLimit: 30000000
        },
        sendAsync: [Function: bound sendAsync],
        send: [Function: bound send],
        _sendJsonRpcRequest: [Function: bound _sendJsonRpcRequest] AsyncFunction
      },
      _eventLoopCache: { detectNetwork: null },
      _network: { chainId: 31337, name: 'unknown' }
    },
    signer: SignerWithAddress {
      _isSigner: true,
      address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
      _signer: JsonRpcSigner {
        _isSigner: true,
        provider: [EthersProviderWrapper],
        _address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
        _index: null
      },
      provider: EthersProviderWrapper {
        _isProvider: true,
        _events: [],
        _emitted: [Object],
        formatter: [Formatter],
        anyNetwork: false,
        _networkPromise: [Promise],
        _maxInternalBlockNumber: -1024,
        _lastBlockNumber: -2,
        _pollingInterval: 4000,
        _fastQueryDate: 0,
        connection: [Object],
        _nextId: 42,
        _hardhatProvider: BackwardsCompatibilityProviderAdapter {
          _wrapped: FixedGasProvider {
            _wrapped: AutomaticSenderProvider {
              _wrapped: [HardhatNetworkProvider],
              _wrappedProvider: [HardhatNetworkProvider]
            },
            _wrappedProvider: AutomaticSenderProvider {
              _wrapped: [HardhatNetworkProvider],
              _wrappedProvider: [HardhatNetworkProvider]
            },
            _gasLimit: 30000000
          },
          _provider: FixedGasProvider {
            _wrapped: AutomaticSenderProvider {
              _wrapped: [HardhatNetworkProvider],
              _wrappedProvider: [HardhatNetworkProvider]
            },
            _wrappedProvider: AutomaticSenderProvider {
              _wrapped: [HardhatNetworkProvider],
              _wrappedProvider: [HardhatNetworkProvider]
            },
            _gasLimit: 30000000
          },
          sendAsync: [Function: bound sendAsync],
          send: [Function: bound send],
          _sendJsonRpcRequest: [Function: bound _sendJsonRpcRequest] AsyncFunction
        },
        _eventLoopCache: [Object],
        _network: [Object]
      }
    },
    callStatic: {
      'ADDRESSES_PROVIDER()': [Function (anonymous)],
      'BRIDGE_PROTOCOL_FEE()': [Function (anonymous)],
      'FLASHLOAN_PREMIUM_TOTAL()': [Function (anonymous)],
      'FLASHLOAN_PREMIUM_TO_PROTOCOL()': [Function (anonymous)],
      'MAX_NUMBER_RESERVES()': [Function (anonymous)],
      'MAX_STABLE_RATE_BORROW_SIZE_PERCENT()': [Function (anonymous)],
      'backUnbacked(address,uint256,uint256)': [Function (anonymous)],
      'borrow(address,uint256,uint256,uint16,address)': [Function (anonymous)],
      'configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))': [Function (anonymous)],
      'deposit(address,uint256,address,uint16)': [Function (anonymous)],
      'dropReserve(address)': [Function (anonymous)],
      'finalizeTransfer(address,address,address,uint256,uint256,uint256)': [Function (anonymous)],
      'flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)': [Function (anonymous)],
      'flashLoanSimple(address,address,uint256,bytes,uint16)': [Function (anonymous)],
      'getConfiguration(address)': [Function (anonymous)],
      'getEModeCategoryData(uint8)': [Function (anonymous)],
      'getReserveAddressById(uint16)': [Function (anonymous)],
      'getReserveData(address)': [Function (anonymous)],
      'getReserveNormalizedIncome(address)': [Function (anonymous)],
      'getReserveNormalizedVariableDebt(address)': [Function (anonymous)],
      'getReservesList()': [Function (anonymous)],
      'getUserAccountData(address)': [Function (anonymous)],
      'getUserConfiguration(address)': [Function (anonymous)],
      'getUserEMode(address)': [Function (anonymous)],
      'initReserve(address,address,address,address,address)': [Function (anonymous)],
      'liquidationCall(address,address,address,uint256,bool)': [Function (anonymous)],
      'mintToTreasury(address[])': [Function (anonymous)],
      'mintUnbacked(address,uint256,address,uint16)': [Function (anonymous)],
      'rebalanceStableBorrowRate(address,address)': [Function (anonymous)],
      'repay(address,uint256,uint256,address)': [Function (anonymous)],
      'repayWithATokens(address,uint256,uint256)': [Function (anonymous)],
      'repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
      'rescueTokens(address,address,uint256)': [Function (anonymous)],
      'resetIsolationModeTotalDebt(address)': [Function (anonymous)],
      'setConfiguration(address,(uint256))': [Function (anonymous)],
      'setReserveInterestRateStrategyAddress(address,address)': [Function (anonymous)],
      'setUserEMode(uint8)': [Function (anonymous)],
      'setUserUseReserveAsCollateral(address,bool)': [Function (anonymous)],
      'supply(address,uint256,address,uint16)': [Function (anonymous)],
      'supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
      'swapBorrowRateMode(address,uint256)': [Function (anonymous)],
      'updateBridgeProtocolFee(uint256)': [Function (anonymous)],
      'updateFlashloanPremiums(uint128,uint128)': [Function (anonymous)],
      'withdraw(address,uint256,address)': [Function (anonymous)],
      ADDRESSES_PROVIDER: [Function (anonymous)],
      BRIDGE_PROTOCOL_FEE: [Function (anonymous)],
      FLASHLOAN_PREMIUM_TOTAL: [Function (anonymous)],
      FLASHLOAN_PREMIUM_TO_PROTOCOL: [Function (anonymous)],
      MAX_NUMBER_RESERVES: [Function (anonymous)],
      MAX_STABLE_RATE_BORROW_SIZE_PERCENT: [Function (anonymous)],
      backUnbacked: [Function (anonymous)],
      borrow: [Function (anonymous)],
      configureEModeCategory: [Function (anonymous)],
      deposit: [Function (anonymous)],
      dropReserve: [Function (anonymous)],
      finalizeTransfer: [Function (anonymous)],
      flashLoan: [Function (anonymous)],
      flashLoanSimple: [Function (anonymous)],
      getConfiguration: [Function (anonymous)],
      getEModeCategoryData: [Function (anonymous)],
      getReserveAddressById: [Function (anonymous)],
      getReserveData: [Function (anonymous)],
      getReserveNormalizedIncome: [Function (anonymous)],
      getReserveNormalizedVariableDebt: [Function (anonymous)],
      getReservesList: [Function (anonymous)],
      getUserAccountData: [Function (anonymous)],
      getUserConfiguration: [Function (anonymous)],
      getUserEMode: [Function (anonymous)],
      initReserve: [Function (anonymous)],
      liquidationCall: [Function (anonymous)],
      mintToTreasury: [Function (anonymous)],
      mintUnbacked: [Function (anonymous)],
      rebalanceStableBorrowRate: [Function (anonymous)],
      repay: [Function (anonymous)],
      repayWithATokens: [Function (anonymous)],
      repayWithPermit: [Function (anonymous)],
      rescueTokens: [Function (anonymous)],
      resetIsolationModeTotalDebt: [Function (anonymous)],
      setConfiguration: [Function (anonymous)],
      setReserveInterestRateStrategyAddress: [Function (anonymous)],
      setUserEMode: [Function (anonymous)],
      setUserUseReserveAsCollateral: [Function (anonymous)],
      supply: [Function (anonymous)],
      supplyWithPermit: [Function (anonymous)],
      swapBorrowRateMode: [Function (anonymous)],
      updateBridgeProtocolFee: [Function (anonymous)],
      updateFlashloanPremiums: [Function (anonymous)],
      withdraw: [Function (anonymous)]
    },
    estimateGas: {
      'ADDRESSES_PROVIDER()': [Function (anonymous)],
      'BRIDGE_PROTOCOL_FEE()': [Function (anonymous)],
      'FLASHLOAN_PREMIUM_TOTAL()': [Function (anonymous)],
      'FLASHLOAN_PREMIUM_TO_PROTOCOL()': [Function (anonymous)],
      'MAX_NUMBER_RESERVES()': [Function (anonymous)],
      'MAX_STABLE_RATE_BORROW_SIZE_PERCENT()': [Function (anonymous)],
      'backUnbacked(address,uint256,uint256)': [Function (anonymous)],
      'borrow(address,uint256,uint256,uint16,address)': [Function (anonymous)],
      'configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))': [Function (anonymous)],
      'deposit(address,uint256,address,uint16)': [Function (anonymous)],
      'dropReserve(address)': [Function (anonymous)],
      'finalizeTransfer(address,address,address,uint256,uint256,uint256)': [Function (anonymous)],
      'flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)': [Function (anonymous)],
      'flashLoanSimple(address,address,uint256,bytes,uint16)': [Function (anonymous)],
      'getConfiguration(address)': [Function (anonymous)],
      'getEModeCategoryData(uint8)': [Function (anonymous)],
      'getReserveAddressById(uint16)': [Function (anonymous)],
      'getReserveData(address)': [Function (anonymous)],
      'getReserveNormalizedIncome(address)': [Function (anonymous)],
      'getReserveNormalizedVariableDebt(address)': [Function (anonymous)],
      'getReservesList()': [Function (anonymous)],
      'getUserAccountData(address)': [Function (anonymous)],
      'getUserConfiguration(address)': [Function (anonymous)],
      'getUserEMode(address)': [Function (anonymous)],
      'initReserve(address,address,address,address,address)': [Function (anonymous)],
      'liquidationCall(address,address,address,uint256,bool)': [Function (anonymous)],
      'mintToTreasury(address[])': [Function (anonymous)],
      'mintUnbacked(address,uint256,address,uint16)': [Function (anonymous)],
      'rebalanceStableBorrowRate(address,address)': [Function (anonymous)],
      'repay(address,uint256,uint256,address)': [Function (anonymous)],
      'repayWithATokens(address,uint256,uint256)': [Function (anonymous)],
      'repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
      'rescueTokens(address,address,uint256)': [Function (anonymous)],
      'resetIsolationModeTotalDebt(address)': [Function (anonymous)],
      'setConfiguration(address,(uint256))': [Function (anonymous)],
      'setReserveInterestRateStrategyAddress(address,address)': [Function (anonymous)],
      'setUserEMode(uint8)': [Function (anonymous)],
      'setUserUseReserveAsCollateral(address,bool)': [Function (anonymous)],
      'supply(address,uint256,address,uint16)': [Function (anonymous)],
      'supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
      'swapBorrowRateMode(address,uint256)': [Function (anonymous)],
      'updateBridgeProtocolFee(uint256)': [Function (anonymous)],
      'updateFlashloanPremiums(uint128,uint128)': [Function (anonymous)],
      'withdraw(address,uint256,address)': [Function (anonymous)],
      ADDRESSES_PROVIDER: [Function (anonymous)],
      BRIDGE_PROTOCOL_FEE: [Function (anonymous)],
      FLASHLOAN_PREMIUM_TOTAL: [Function (anonymous)],
      FLASHLOAN_PREMIUM_TO_PROTOCOL: [Function (anonymous)],
      MAX_NUMBER_RESERVES: [Function (anonymous)],
      MAX_STABLE_RATE_BORROW_SIZE_PERCENT: [Function (anonymous)],
      backUnbacked: [Function (anonymous)],
      borrow: [Function (anonymous)],
      configureEModeCategory: [Function (anonymous)],
      deposit: [Function (anonymous)],
      dropReserve: [Function (anonymous)],
      finalizeTransfer: [Function (anonymous)],
      flashLoan: [Function (anonymous)],
      flashLoanSimple: [Function (anonymous)],
      getConfiguration: [Function (anonymous)],
      getEModeCategoryData: [Function (anonymous)],
      getReserveAddressById: [Function (anonymous)],
      getReserveData: [Function (anonymous)],
      getReserveNormalizedIncome: [Function (anonymous)],
      getReserveNormalizedVariableDebt: [Function (anonymous)],
      getReservesList: [Function (anonymous)],
      getUserAccountData: [Function (anonymous)],
      getUserConfiguration: [Function (anonymous)],
      getUserEMode: [Function (anonymous)],
      initReserve: [Function (anonymous)],
      liquidationCall: [Function (anonymous)],
      mintToTreasury: [Function (anonymous)],
      mintUnbacked: [Function (anonymous)],
      rebalanceStableBorrowRate: [Function (anonymous)],
      repay: [Function (anonymous)],
      repayWithATokens: [Function (anonymous)],
      repayWithPermit: [Function (anonymous)],
      rescueTokens: [Function (anonymous)],
      resetIsolationModeTotalDebt: [Function (anonymous)],
      setConfiguration: [Function (anonymous)],
      setReserveInterestRateStrategyAddress: [Function (anonymous)],
      setUserEMode: [Function (anonymous)],
      setUserUseReserveAsCollateral: [Function (anonymous)],
      supply: [Function (anonymous)],
      supplyWithPermit: [Function (anonymous)],
      swapBorrowRateMode: [Function (anonymous)],
      updateBridgeProtocolFee: [Function (anonymous)],
      updateFlashloanPremiums: [Function (anonymous)],
      withdraw: [Function (anonymous)]
    },
    functions: {
      'ADDRESSES_PROVIDER()': [Function (anonymous)],
      'BRIDGE_PROTOCOL_FEE()': [Function (anonymous)],
      'FLASHLOAN_PREMIUM_TOTAL()': [Function (anonymous)],
      'FLASHLOAN_PREMIUM_TO_PROTOCOL()': [Function (anonymous)],
      'MAX_NUMBER_RESERVES()': [Function (anonymous)],
      'MAX_STABLE_RATE_BORROW_SIZE_PERCENT()': [Function (anonymous)],
      'backUnbacked(address,uint256,uint256)': [Function (anonymous)],
      'borrow(address,uint256,uint256,uint16,address)': [Function (anonymous)],
      'configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))': [Function (anonymous)],
      'deposit(address,uint256,address,uint16)': [Function (anonymous)],
      'dropReserve(address)': [Function (anonymous)],
      'finalizeTransfer(address,address,address,uint256,uint256,uint256)': [Function (anonymous)],
      'flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)': [Function (anonymous)],
      'flashLoanSimple(address,address,uint256,bytes,uint16)': [Function (anonymous)],
      'getConfiguration(address)': [Function (anonymous)],
      'getEModeCategoryData(uint8)': [Function (anonymous)],
      'getReserveAddressById(uint16)': [Function (anonymous)],
      'getReserveData(address)': [Function (anonymous)],
      'getReserveNormalizedIncome(address)': [Function (anonymous)],
      'getReserveNormalizedVariableDebt(address)': [Function (anonymous)],
      'getReservesList()': [Function (anonymous)],
      'getUserAccountData(address)': [Function (anonymous)],
      'getUserConfiguration(address)': [Function (anonymous)],
      'getUserEMode(address)': [Function (anonymous)],
      'initReserve(address,address,address,address,address)': [Function (anonymous)],
      'liquidationCall(address,address,address,uint256,bool)': [Function (anonymous)],
      'mintToTreasury(address[])': [Function (anonymous)],
      'mintUnbacked(address,uint256,address,uint16)': [Function (anonymous)],
      'rebalanceStableBorrowRate(address,address)': [Function (anonymous)],
      'repay(address,uint256,uint256,address)': [Function (anonymous)],
      'repayWithATokens(address,uint256,uint256)': [Function (anonymous)],
      'repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
      'rescueTokens(address,address,uint256)': [Function (anonymous)],
      'resetIsolationModeTotalDebt(address)': [Function (anonymous)],
      'setConfiguration(address,(uint256))': [Function (anonymous)],
      'setReserveInterestRateStrategyAddress(address,address)': [Function (anonymous)],
      'setUserEMode(uint8)': [Function (anonymous)],
      'setUserUseReserveAsCollateral(address,bool)': [Function (anonymous)],
      'supply(address,uint256,address,uint16)': [Function (anonymous)],
      'supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
      'swapBorrowRateMode(address,uint256)': [Function (anonymous)],
      'updateBridgeProtocolFee(uint256)': [Function (anonymous)],
      'updateFlashloanPremiums(uint128,uint128)': [Function (anonymous)],
      'withdraw(address,uint256,address)': [Function (anonymous)],
      ADDRESSES_PROVIDER: [Function (anonymous)],
      BRIDGE_PROTOCOL_FEE: [Function (anonymous)],
      FLASHLOAN_PREMIUM_TOTAL: [Function (anonymous)],
      FLASHLOAN_PREMIUM_TO_PROTOCOL: [Function (anonymous)],
      MAX_NUMBER_RESERVES: [Function (anonymous)],
      MAX_STABLE_RATE_BORROW_SIZE_PERCENT: [Function (anonymous)],
      backUnbacked: [Function (anonymous)],
      borrow: [Function (anonymous)],
      configureEModeCategory: [Function (anonymous)],
      deposit: [Function (anonymous)],
      dropReserve: [Function (anonymous)],
      finalizeTransfer: [Function (anonymous)],
      flashLoan: [Function (anonymous)],
      flashLoanSimple: [Function (anonymous)],
      getConfiguration: [Function (anonymous)],
      getEModeCategoryData: [Function (anonymous)],
      getReserveAddressById: [Function (anonymous)],
      getReserveData: [Function (anonymous)],
      getReserveNormalizedIncome: [Function (anonymous)],
      getReserveNormalizedVariableDebt: [Function (anonymous)],
      getReservesList: [Function (anonymous)],
      getUserAccountData: [Function (anonymous)],
      getUserConfiguration: [Function (anonymous)],
      getUserEMode: [Function (anonymous)],
      initReserve: [Function (anonymous)],
      liquidationCall: [Function (anonymous)],
      mintToTreasury: [Function (anonymous)],
      mintUnbacked: [Function (anonymous)],
      rebalanceStableBorrowRate: [Function (anonymous)],
      repay: [Function (anonymous)],
      repayWithATokens: [Function (anonymous)],
      repayWithPermit: [Function (anonymous)],
      rescueTokens: [Function (anonymous)],
      resetIsolationModeTotalDebt: [Function (anonymous)],
      setConfiguration: [Function (anonymous)],
      setReserveInterestRateStrategyAddress: [Function (anonymous)],
      setUserEMode: [Function (anonymous)],
      setUserUseReserveAsCollateral: [Function (anonymous)],
      supply: [Function (anonymous)],
      supplyWithPermit: [Function (anonymous)],
      swapBorrowRateMode: [Function (anonymous)],
      updateBridgeProtocolFee: [Function (anonymous)],
      updateFlashloanPremiums: [Function (anonymous)],
      withdraw: [Function (anonymous)]
    },
    populateTransaction: {
      'ADDRESSES_PROVIDER()': [Function (anonymous)],
      'BRIDGE_PROTOCOL_FEE()': [Function (anonymous)],
      'FLASHLOAN_PREMIUM_TOTAL()': [Function (anonymous)],
      'FLASHLOAN_PREMIUM_TO_PROTOCOL()': [Function (anonymous)],
      'MAX_NUMBER_RESERVES()': [Function (anonymous)],
      'MAX_STABLE_RATE_BORROW_SIZE_PERCENT()': [Function (anonymous)],
      'backUnbacked(address,uint256,uint256)': [Function (anonymous)],
      'borrow(address,uint256,uint256,uint16,address)': [Function (anonymous)],
      'configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))': [Function (anonymous)],
      'deposit(address,uint256,address,uint16)': [Function (anonymous)],
      'dropReserve(address)': [Function (anonymous)],
      'finalizeTransfer(address,address,address,uint256,uint256,uint256)': [Function (anonymous)],
      'flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)': [Function (anonymous)],
      'flashLoanSimple(address,address,uint256,bytes,uint16)': [Function (anonymous)],
      'getConfiguration(address)': [Function (anonymous)],
      'getEModeCategoryData(uint8)': [Function (anonymous)],
      'getReserveAddressById(uint16)': [Function (anonymous)],
      'getReserveData(address)': [Function (anonymous)],
      'getReserveNormalizedIncome(address)': [Function (anonymous)],
      'getReserveNormalizedVariableDebt(address)': [Function (anonymous)],
      'getReservesList()': [Function (anonymous)],
      'getUserAccountData(address)': [Function (anonymous)],
      'getUserConfiguration(address)': [Function (anonymous)],
      'getUserEMode(address)': [Function (anonymous)],
      'initReserve(address,address,address,address,address)': [Function (anonymous)],
      'liquidationCall(address,address,address,uint256,bool)': [Function (anonymous)],
      'mintToTreasury(address[])': [Function (anonymous)],
      'mintUnbacked(address,uint256,address,uint16)': [Function (anonymous)],
      'rebalanceStableBorrowRate(address,address)': [Function (anonymous)],
      'repay(address,uint256,uint256,address)': [Function (anonymous)],
      'repayWithATokens(address,uint256,uint256)': [Function (anonymous)],
      'repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
      'rescueTokens(address,address,uint256)': [Function (anonymous)],
      'resetIsolationModeTotalDebt(address)': [Function (anonymous)],
      'setConfiguration(address,(uint256))': [Function (anonymous)],
      'setReserveInterestRateStrategyAddress(address,address)': [Function (anonymous)],
      'setUserEMode(uint8)': [Function (anonymous)],
      'setUserUseReserveAsCollateral(address,bool)': [Function (anonymous)],
      'supply(address,uint256,address,uint16)': [Function (anonymous)],
      'supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
      'swapBorrowRateMode(address,uint256)': [Function (anonymous)],
      'updateBridgeProtocolFee(uint256)': [Function (anonymous)],
      'updateFlashloanPremiums(uint128,uint128)': [Function (anonymous)],
      'withdraw(address,uint256,address)': [Function (anonymous)],
      ADDRESSES_PROVIDER: [Function (anonymous)],
      BRIDGE_PROTOCOL_FEE: [Function (anonymous)],
      FLASHLOAN_PREMIUM_TOTAL: [Function (anonymous)],
      FLASHLOAN_PREMIUM_TO_PROTOCOL: [Function (anonymous)],
      MAX_NUMBER_RESERVES: [Function (anonymous)],
      MAX_STABLE_RATE_BORROW_SIZE_PERCENT: [Function (anonymous)],
      backUnbacked: [Function (anonymous)],
      borrow: [Function (anonymous)],
      configureEModeCategory: [Function (anonymous)],
      deposit: [Function (anonymous)],
      dropReserve: [Function (anonymous)],
      finalizeTransfer: [Function (anonymous)],
      flashLoan: [Function (anonymous)],
      flashLoanSimple: [Function (anonymous)],
      getConfiguration: [Function (anonymous)],
      getEModeCategoryData: [Function (anonymous)],
      getReserveAddressById: [Function (anonymous)],
      getReserveData: [Function (anonymous)],
      getReserveNormalizedIncome: [Function (anonymous)],
      getReserveNormalizedVariableDebt: [Function (anonymous)],
      getReservesList: [Function (anonymous)],
      getUserAccountData: [Function (anonymous)],
      getUserConfiguration: [Function (anonymous)],
      getUserEMode: [Function (anonymous)],
      initReserve: [Function (anonymous)],
      liquidationCall: [Function (anonymous)],
      mintToTreasury: [Function (anonymous)],
      mintUnbacked: [Function (anonymous)],
      rebalanceStableBorrowRate: [Function (anonymous)],
      repay: [Function (anonymous)],
      repayWithATokens: [Function (anonymous)],
      repayWithPermit: [Function (anonymous)],
      rescueTokens: [Function (anonymous)],
      resetIsolationModeTotalDebt: [Function (anonymous)],
      setConfiguration: [Function (anonymous)],
      setReserveInterestRateStrategyAddress: [Function (anonymous)],
      setUserEMode: [Function (anonymous)],
      setUserUseReserveAsCollateral: [Function (anonymous)],
      supply: [Function (anonymous)],
      supplyWithPermit: [Function (anonymous)],
      swapBorrowRateMode: [Function (anonymous)],
      updateBridgeProtocolFee: [Function (anonymous)],
      updateFlashloanPremiums: [Function (anonymous)],
      withdraw: [Function (anonymous)]
    },
    filters: {
      'BackUnbacked(address,address,uint256,uint256)': [Function (anonymous)],
      'Borrow(address,address,address,uint256,uint8,uint256,uint16)': [Function (anonymous)],
      'FlashLoan(address,address,address,uint256,uint8,uint256,uint16)': [Function (anonymous)],
      'IsolationModeTotalDebtUpdated(address,uint256)': [Function (anonymous)],
      'LiquidationCall(address,address,address,uint256,uint256,address,bool)': [Function (anonymous)],
      'MintUnbacked(address,address,address,uint256,uint16)': [Function (anonymous)],
      'MintedToTreasury(address,uint256)': [Function (anonymous)],
      'RebalanceStableBorrowRate(address,address)': [Function (anonymous)],
      'Repay(address,address,address,uint256,bool)': [Function (anonymous)],
      'ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)': [Function (anonymous)],
      'ReserveUsedAsCollateralDisabled(address,address)': [Function (anonymous)],
      'ReserveUsedAsCollateralEnabled(address,address)': [Function (anonymous)],
      'Supply(address,address,address,uint256,uint16)': [Function (anonymous)],
      'SwapBorrowRateMode(address,address,uint8)': [Function (anonymous)],
      'UserEModeSet(address,uint8)': [Function (anonymous)],
      'Withdraw(address,address,address,uint256)': [Function (anonymous)],
      BackUnbacked: [Function (anonymous)],
      Borrow: [Function (anonymous)],
      FlashLoan: [Function (anonymous)],
      IsolationModeTotalDebtUpdated: [Function (anonymous)],
      LiquidationCall: [Function (anonymous)],
      MintUnbacked: [Function (anonymous)],
      MintedToTreasury: [Function (anonymous)],
      RebalanceStableBorrowRate: [Function (anonymous)],
      Repay: [Function (anonymous)],
      ReserveDataUpdated: [Function (anonymous)],
      ReserveUsedAsCollateralDisabled: [Function (anonymous)],
      ReserveUsedAsCollateralEnabled: [Function (anonymous)],
      Supply: [Function (anonymous)],
      SwapBorrowRateMode: [Function (anonymous)],
      UserEModeSet: [Function (anonymous)],
      Withdraw: [Function (anonymous)]
    },
    _runningEvents: {},
    _wrappedEmits: {},
    address: '0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2',
    resolvedAddress: Promise { '0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2' },
    'ADDRESSES_PROVIDER()': [Function (anonymous)],
    'BRIDGE_PROTOCOL_FEE()': [Function (anonymous)],
    'FLASHLOAN_PREMIUM_TOTAL()': [Function (anonymous)],
    'FLASHLOAN_PREMIUM_TO_PROTOCOL()': [Function (anonymous)],
    'MAX_NUMBER_RESERVES()': [Function (anonymous)],
    'MAX_STABLE_RATE_BORROW_SIZE_PERCENT()': [Function (anonymous)],
    'backUnbacked(address,uint256,uint256)': [Function (anonymous)],
    'borrow(address,uint256,uint256,uint16,address)': [Function (anonymous)],
    'configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))': [Function (anonymous)],
    'deposit(address,uint256,address,uint16)': [Function (anonymous)],
    'dropReserve(address)': [Function (anonymous)],
    'finalizeTransfer(address,address,address,uint256,uint256,uint256)': [Function (anonymous)],
    'flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)': [Function (anonymous)],
    'flashLoanSimple(address,address,uint256,bytes,uint16)': [Function (anonymous)],
    'getConfiguration(address)': [Function (anonymous)],
    'getEModeCategoryData(uint8)': [Function (anonymous)],
    'getReserveAddressById(uint16)': [Function (anonymous)],
    'getReserveData(address)': [Function (anonymous)],
    'getReserveNormalizedIncome(address)': [Function (anonymous)],
    'getReserveNormalizedVariableDebt(address)': [Function (anonymous)],
    'getReservesList()': [Function (anonymous)],
    'getUserAccountData(address)': [Function (anonymous)],
    'getUserConfiguration(address)': [Function (anonymous)],
    'getUserEMode(address)': [Function (anonymous)],
    'initReserve(address,address,address,address,address)': [Function (anonymous)],
    'liquidationCall(address,address,address,uint256,bool)': [Function (anonymous)],
    'mintToTreasury(address[])': [Function (anonymous)],
    'mintUnbacked(address,uint256,address,uint16)': [Function (anonymous)],
    'rebalanceStableBorrowRate(address,address)': [Function (anonymous)],
    'repay(address,uint256,uint256,address)': [Function (anonymous)],
    'repayWithATokens(address,uint256,uint256)': [Function (anonymous)],
    'repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
    'rescueTokens(address,address,uint256)': [Function (anonymous)],
    'resetIsolationModeTotalDebt(address)': [Function (anonymous)],
    'setConfiguration(address,(uint256))': [Function (anonymous)],
    'setReserveInterestRateStrategyAddress(address,address)': [Function (anonymous)],
    'setUserEMode(uint8)': [Function (anonymous)],
    'setUserUseReserveAsCollateral(address,bool)': [Function (anonymous)],
    'supply(address,uint256,address,uint16)': [Function (anonymous)],
    'supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)': [Function (anonymous)],
    'swapBorrowRateMode(address,uint256)': [Function (anonymous)],
    'updateBridgeProtocolFee(uint256)': [Function (anonymous)],
    'updateFlashloanPremiums(uint128,uint128)': [Function (anonymous)],
    'withdraw(address,uint256,address)': [Function (anonymous)],
    ADDRESSES_PROVIDER: [Function (anonymous)],
    BRIDGE_PROTOCOL_FEE: [Function (anonymous)],
    FLASHLOAN_PREMIUM_TOTAL: [Function (anonymous)],
    FLASHLOAN_PREMIUM_TO_PROTOCOL: [Function (anonymous)],
    MAX_NUMBER_RESERVES: [Function (anonymous)],
    MAX_STABLE_RATE_BORROW_SIZE_PERCENT: [Function (anonymous)],
    backUnbacked: [Function (anonymous)],
    borrow: [Function (anonymous)],
    configureEModeCategory: [Function (anonymous)],
    deposit: [Function (anonymous)],
    dropReserve: [Function (anonymous)],
    finalizeTransfer: [Function (anonymous)],
    flashLoan: [Function (anonymous)],
    flashLoanSimple: [Function (anonymous)],
    getConfiguration: [Function (anonymous)],
    getEModeCategoryData: [Function (anonymous)],
    getReserveAddressById: [Function (anonymous)],
    getReserveData: [Function (anonymous)],
    getReserveNormalizedIncome: [Function (anonymous)],
    getReserveNormalizedVariableDebt: [Function (anonymous)],
    getReservesList: [Function (anonymous)],
    getUserAccountData: [Function (anonymous)],
    getUserConfiguration: [Function (anonymous)],
    getUserEMode: [Function (anonymous)],
    initReserve: [Function (anonymous)],
    liquidationCall: [Function (anonymous)],
    mintToTreasury: [Function (anonymous)],
    mintUnbacked: [Function (anonymous)],
    rebalanceStableBorrowRate: [Function (anonymous)],
    repay: [Function (anonymous)],
    repayWithATokens: [Function (anonymous)],
    repayWithPermit: [Function (anonymous)],
    rescueTokens: [Function (anonymous)],
    resetIsolationModeTotalDebt: [Function (anonymous)],
    setConfiguration: [Function (anonymous)],
    setReserveInterestRateStrategyAddress: [Function (anonymous)],
    setUserEMode: [Function (anonymous)],
    setUserUseReserveAsCollateral: [Function (anonymous)],
    supply: [Function (anonymous)],
    supplyWithPermit: [Function (anonymous)],
    swapBorrowRateMode: [Function (anonymous)],
    updateBridgeProtocolFee: [Function (anonymous)],
    updateFlashloanPremiums: [Function (anonymous)],
    withdraw: [Function (anonymous)]
  }